// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// flat_OP_1D
List flat_OP_1D(const std::vector<double>& inData, Nullable<double> inPenalty);
RcppExport SEXP _dust_flat_OP_1D(SEXP inDataSEXP, SEXP inPenaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type inData(inDataSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type inPenalty(inPenaltySEXP);
    rcpp_result_gen = Rcpp::wrap(flat_OP_1D(inData, inPenalty));
    return rcpp_result_gen;
END_RCPP
}
// flat_OP_MD
List flat_OP_MD(const arma::dmat& inData, Nullable<double> inPenalty);
RcppExport SEXP _dust_flat_OP_MD(SEXP inDataSEXP, SEXP inPenaltySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::dmat& >::type inData(inDataSEXP);
    Rcpp::traits::input_parameter< Nullable<double> >::type inPenalty(inPenaltySEXP);
    rcpp_result_gen = Rcpp::wrap(flat_OP_MD(inData, inPenalty));
    return rcpp_result_gen;
END_RCPP
}
// sdDiff
double sdDiff(std::vector<double>& y, std::string method);
RcppExport SEXP _dust_sdDiff(SEXP ySEXP, SEXP methodSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type method(methodSEXP);
    rcpp_result_gen = Rcpp::wrap(sdDiff(y, method));
    return rcpp_result_gen;
END_RCPP
}
// data_normalization_1D
std::vector<double> data_normalization_1D(std::vector<double>& y, std::string type);
RcppExport SEXP _dust_data_normalization_1D(SEXP ySEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< std::vector<double>& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(data_normalization_1D(y, type));
    return rcpp_result_gen;
END_RCPP
}
// data_normalization_MD
NumericMatrix data_normalization_MD(NumericMatrix& y, std::string type);
RcppExport SEXP _dust_data_normalization_MD(SEXP ySEXP, SEXP typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix& >::type y(ySEXP);
    Rcpp::traits::input_parameter< std::string >::type type(typeSEXP);
    rcpp_result_gen = Rcpp::wrap(data_normalization_MD(y, type));
    return rcpp_result_gen;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_DUSTMODULE1D();
RcppExport SEXP _rcpp_module_boot_DUSTMODULE2D();
RcppExport SEXP _rcpp_module_boot_FLATOP1D();
RcppExport SEXP _rcpp_module_boot_FLATOPMD();
RcppExport SEXP _rcpp_module_boot_FLATDUST1D();
RcppExport SEXP _rcpp_module_boot_FLAT2DUST1D();

static const R_CallMethodDef CallEntries[] = {
    {"_dust_flat_OP_1D", (DL_FUNC) &_dust_flat_OP_1D, 2},
    {"_dust_flat_OP_MD", (DL_FUNC) &_dust_flat_OP_MD, 2},
    {"_dust_sdDiff", (DL_FUNC) &_dust_sdDiff, 2},
    {"_dust_data_normalization_1D", (DL_FUNC) &_dust_data_normalization_1D, 2},
    {"_dust_data_normalization_MD", (DL_FUNC) &_dust_data_normalization_MD, 2},
    {"_rcpp_module_boot_DUSTMODULE1D", (DL_FUNC) &_rcpp_module_boot_DUSTMODULE1D, 0},
    {"_rcpp_module_boot_DUSTMODULE2D", (DL_FUNC) &_rcpp_module_boot_DUSTMODULE2D, 0},
    {"_rcpp_module_boot_FLATOP1D", (DL_FUNC) &_rcpp_module_boot_FLATOP1D, 0},
    {"_rcpp_module_boot_FLATOPMD", (DL_FUNC) &_rcpp_module_boot_FLATOPMD, 0},
    {"_rcpp_module_boot_FLATDUST1D", (DL_FUNC) &_rcpp_module_boot_FLATDUST1D, 0},
    {"_rcpp_module_boot_FLAT2DUST1D", (DL_FUNC) &_rcpp_module_boot_FLAT2DUST1D, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_dust(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
