# Build the standalone LaTeX table from the saved benchmark output.
write_meanvar_table <- function(out_dir) {
  run <- readRDS(file.path(out_dir, "timings.rds"))
  timings <- run$timings
  summary <- run$summary
  segment_counts <- c(1e4L, 1e3L, 1e2L, 10L, 1L)

  cell <- function(method, nb_seg) {
    row <- summary[summary$method == method & summary$nb_seg == nb_seg, ]
    fastest <- min(summary$mean_s[summary$nb_seg == nb_seg])
    mean_text <- sprintf("%.3g", row$mean_s)
    if (row$mean_s == fastest) mean_text <- paste0("\\mathbf{", mean_text, "}")
    sprintf("$%s\\,(%.2g)$", mean_text, row$sd_s)
  }
  success_10k_1d <- sum(timings$segments_detected[
    timings$nb_seg == 10000L & timings$method == "1D"] == 10000L)
  success_10k_2d <- sum(timings$segments_detected[
    timings$nb_seg == 10000L & timings$method == "2D"] == 10000L)

  lines <- c(
    "% Generated by run_time_meanVar.R; times are in seconds.",
    sprintf("%% n = %d; repetitions = %d; seed base = %d; dust version = %s.",
            run$n, run$repetitions, run$base_seed, run$dust_version),
    "\\documentclass{article}",
    "\\usepackage[margin=1in]{geometry}",
    "\\begin{document}",
    "\\begin{table}[!ht]",
    sprintf(paste0("\\caption{Mean execution time (seconds) over %d repetitions for a length-$n=10^6$ ",
                   "series with regularly spaced mean/variance segments. Parentheses give the sample ",
                   "standard deviation; the fastest mean is bold. We used penalty $\\beta=2\\log(n)$. ",
                   "Both methods detected all segments in every repetition for $10^3$ segments or fewer. ",
                   "For $10^4$ segments, the one- and two-constraint methods detected all segments in ",
                   "%d and %d repetitions, respectively.}\\label{tab:meanVar-time}"),
            run$repetitions, success_10k_1d, success_10k_2d),
    "\\begin{tabular}{l|rrrrr}",
    "algorithm & $10^4$ seg & $10^3$ seg & $10^2$ seg & $10$ seg & $1$ seg \\\\",
    "\\hline"
  )
  for (method in c("1D", "2D")) {
    label <- if (method == "1D") "DUST (1 constr)" else "DUST (2 constr)"
    values <- vapply(segment_counts, function(k) cell(method, k), character(1L))
    lines <- c(lines, paste(label, "&", paste(values, collapse = " & "), "\\\\"))
  }
  lines <- c(lines, "\\end{tabular}", "\\end{table}", "\\end{document}")
  writeLines(lines, file.path(out_dir, "table_meanVar.tex"))
}

# Run directly to rebuild the table from the existing RDS file.
if (sys.nframe() == 0L) {
  args <- commandArgs(trailingOnly = TRUE)
  script_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  script_file <- sub("^--file=", "", script_arg[1L])
  out_dir <- if (length(args)) args[1L] else dirname(normalizePath(script_file))
  write_meanvar_table(out_dir)
}
