

######################################################
###########     dataGenerator_meanVar   ##############
######################################################

#' dataGenerator_meanVar
#'
#' @description Generating data for detecting changes in mean and variance with Gaussian model
#' @param chpts a vector of increasing change-point indices
#' @param means vector of successive segment means
#' @param sds vector of successive segment standard deviation
#' @return a vector of (univariate) simulated data with changes in mean and variance
#' @examples
#' dataGenerator_meanVar(chpts = c(30,100,120), means = c(0,1,0), sds = c(1,1,2))
dataGenerator_meanVar <- function(chpts = 100,
                                  means = 0,
                                  sds = 1)
{
  ############
  ### STOP ###
  ############
  if(!is.numeric(chpts)){stop('chpts values are not all numeric')}
  if(!all(chpts > 0)){stop('chpts values are not all positives')}
  if(is.unsorted(chpts, strictly = TRUE)){stop('chpts should be a strictly increasing vector of change-point positions (indices)')}

  if(!is.numeric(means)){stop('means values are not all numeric')}
  if(length(chpts) != length(means)){stop('chpts and means vectors are of different size')}
  if(length(chpts) != length(sds)){stop('chpts and sds vectors are of different size')}
  if(min(sds) < 0){stop('sds values not all non-negative')}


  ############  data generation  ############

  n <- chpts[length(chpts)]
  repetition <- c(chpts[1], diff(chpts))

  mu <- rep(means, repetition)
  sds <- rep(sds, repetition)
  y <- rnorm(n, mean = mu, sd = sds)
  return(y)
}


########################################################
#############     dataGenerator_Reg    #################
########################################################

#' dataGenerator_Reg
#'
#' @description Generating data for changes in simple regression model and simple logistic regression model
#' @param chpts a vector of increasing change-point indices
#' @param A vector of regression coefficients A in Ax+B simple regression model
#' @param B vector of regression coefficients B in Ax+B simple regression model
#' @param meansX vector of mean values for x values generated by a Gaussian model (if one value, we copy the value to match chpts length)
#' @param sdX vector of standard deviation values for x values generated by a Gaussian model  (if one value, we copy the value to match chpts length)
#' @param sdNoise standard deviation of the Gaussian noise
#' @param type \code{"simple"} for the simple regression, \code{"logistic"} for the logistic regression
#' @return a dataframe with time series x and y for change-points in regression of type \code{y = Ax + B + noise} or\code{P(Y = 1) = 1/(1+exp(-(Ax+B+noise)))}.  \code{x} and \code{noise} are generated by a random Gaussian model.
#' @examples
#' dataGenerator_Reg(chpts = c(40,90), A = c(2,-1),  B = c(-1,2), meansX = c(1,2), type = "simple")
#' dataGenerator_Reg(chpts = c(50,100), A = c(-1,1),  B = c(1,-1), type = "logistic")
dataGenerator_Reg <- function(chpts = 100,
                              A = 2,
                              B = -1,
                              meansX = 0,
                              sdX = 1,
                              sdNoise = 1,
                              type = "simple")
{
  ############
  ### STOP ###
  ############
  if(!is.numeric(chpts)){stop('chpts values are not all numeric')}
  if(!all(chpts > 0)){stop('chpts values are not all positives')}
  if(is.unsorted(chpts, strictly = TRUE)){stop('chpts should be a strictly increasing vector of change-point positions (indices)')}

  if(length(chpts) != length(A)){stop('chpts and A vectors are of different size')}
  if(length(chpts) != length(B)){stop('chpts and B vectors are of different size')}
  if(min(sdX) < 0){stop('sdX cannot be negative')}

  if(length(meansX) == 1){meansX <- rep(meansX, length(chpts))}
  if(length(sdX) == 1){sdX <- rep(sdX, length(chpts))}
  if(length(chpts) != length(meansX)){stop('chpts and meansX vectors are of different size')}
  if(length(chpts) != length(sdX)){stop('chpts and sdX vectors are of different size')}

  ############  data generation  ############

  n <- chpts[length(chpts)]
  repetition <- c(chpts[1], diff(chpts))
  A_rep <- rep(A, repetition)
  B_rep <- rep(B, repetition)
  meansX_rep <- rep(meansX, repetition)
  sdX_rep <- rep(sdX, repetition)

  x <- rnorm(n, mean = meansX_rep, sd = sdX_rep)

  if(type == "simple")
  {
    y <- A_rep*x + B_rep + rnorm(n, mean = 0, sd = sdNoise)
  }
  if(type == "logistic")
  {
    z <- A_rep*x + B_rep + rnorm(n, mean = 0, sd = sdNoise)
    proba <- 1/(1 + exp(-z))
    y <- rbinom(n, 1, proba)
  }

  return(data.frame(x = x, y = y))
}

