#' Internal S4 classes for DUST C++ modules
#'
#' These S4 classes are generated by Rcpp modules and wrap the underlying
#' C++ implementations in C++. They are not intended to be used directly.
#' Instead, users should rely on the high-level interfaces:
#' \code{\link{dust.1D}}, \code{\link{dust.object.1D}},
#' \code{\link{dust.meanVar}} and \code{\link{dust.object.meanVar}}.
#' \code{\link{dust.Reg}} and \code{\link{dust.object.Reg}}.
#'
#' @name DUST_module_classes
#'
#' @aliases Rcpp_DUST_1D Rcpp_DUST_1D-class
#' @aliases Rcpp_DUST_meanVar Rcpp_DUST_meanVar-class
#' @aliases Rcpp_DUST_Reg Rcpp_DUST_Reg-class
#' @aliases C++Object C++Object-class
#'
#' @docType class
#' @keywords internal
NULL
