#' Internal S4 classes for DUST C++ modules
#'
#' Classes generated by the Rcpp module. Use \code{\link{dust.object.1D}}, \code{\link{dust.object.MD}} and \code{\link{dust.object.meanVar}}.
#'
#' @name DUST_module_classes
#'
#' @seealso \code{\link{Rcpp_Detector-class}}, \code{\link{C++Object-class}}
#'
#' @docType class
#' @keywords internal
NULL
