#' Internal S4 classes for DUST C++ modules
#'
#' Classes generated by the Rcpp modules (1D data). Use \code{\link{dust.1D}} and \code{\link{dust.object.1D}}.
#'
#' @name DUST_module_classes
#'
#' @seealso \code{\link{Rcpp_DUST_1D-class}}, \code{\link{C++Object-class}}
#'
#' @docType class
#' @keywords internal
NULL
