# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' sdDiff
#'
#' @description Estimation of the noise standard deviation from the differences of the data (robust to the changes in mean)
#'
#' @param y a numeric vector
#' @param method \code{"HALL"} (default), \code{"MAD"} or \code{"SD"}
#' \itemize{
#'   \item \code{"HALL"}: Hall estimator (weighted differences)
#'   \item \code{"MAD"}: MAD of the differences
#'   \item \code{"SD"}: standard deviation of the differences
#' }
#' @return the estimated standard deviation
#'
#' @examples
#' y <- dataGenerator_1D(chpts = c(300, 600), parameters = c(0, 1), sdNoise = 2, type = "gauss")
#' sdDiff(y)
#' sdDiff(y, "MAD")
#' sdDiff(y, "SD")
#'
#' @export
sdDiff <- function(y, method = "HALL") {
    .Call(`_dust_sdDiff`, y, method)
}

#' data_normalization_1D
#'
#' @name data_normalization_1D
#'
#' @description Normalization of the data before using dust.1D with the default penalty
#' \itemize{
#'   \item \code{"gauss"}: division by \code{sdDiff(y)}
#'   \item \code{"poisson"}, \code{"exp"}: division by the mean
#'   \item \code{"binom"}, \code{"negbin"}: division by \code{size}
#'   \item \code{"variance"}: the mean is removed
#'   \item \code{"geom"}, \code{"bern"}: no change
#' }
#'
#' @param y a numeric vector
#' @param type the model: \code{"gauss"} (default), \code{"poisson"}, \code{"exp"}, \code{"geom"}, \code{"bern"}, \code{"binom"}, \code{"negbin"}, \code{"variance"}
#' @param size number of trials (binom) or number of successes (negbin). Required for these two models.
#' @return the normalized data
#' @examples
#' y <- dataGenerator_1D(chpts = c(300, 600), parameters = c(0, 1), sdNoise = 2, type = "gauss")
#' sdDiff(data_normalization_1D(y))
#'
#' y <- dataGenerator_1D(chpts = c(300, 600), parameters = c(2, 8), type = "poisson")
#' mean(data_normalization_1D(y, type = "poisson"))
#'
#' y <- dataGenerator_1D(chpts = c(300, 600), parameters = c(0.4, 0.7), nbTrials = 5, type = "binom")
#' data_normalization_1D(y, type = "binom", size = 5)[1:10]
#'
#' @export
data_normalization_1D <- function(y, type = "gauss", size = NA_real_) {
    .Call(`_dust_data_normalization_1D`, y, type, size)
}

